# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Aproject\cvdzy\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1222, 892)
        self.imgButton = QtWidgets.QPushButton(Dialog)
        self.imgButton.setGeometry(QtCore.QRect(250, 730, 91, 41))
        self.imgButton.setObjectName("imgButton")
        self.QRButton1 = QtWidgets.QPushButton(Dialog)
        self.QRButton1.setGeometry(QtCore.QRect(770, 670, 91, 41))
        self.QRButton1.setObjectName("QRButton1")
        self.carButton1 = QtWidgets.QPushButton(Dialog)
        self.carButton1.setGeometry(QtCore.QRect(890, 670, 91, 41))
        self.carButton1.setObjectName("carButton1")
        self.faceButton1 = QtWidgets.QPushButton(Dialog)
        self.faceButton1.setGeometry(QtCore.QRect(1010, 670, 91, 41))
        self.faceButton1.setObjectName("faceButton1")
        self.inlabel = QtWidgets.QLabel(Dialog)
        self.inlabel.setGeometry(QtCore.QRect(10, 50, 591, 541))
        self.inlabel.setScaledContents(True)
        self.inlabel.setObjectName("inlabel")
        self.outlabel = QtWidgets.QLabel(Dialog)
        self.outlabel.setGeometry(QtCore.QRect(650, 50, 561, 541))
        self.outlabel.setScaledContents(True)
        self.outlabel.setObjectName("outlabel")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(110, 630, 371, 161))
        self.groupBox.setObjectName("groupBox")
        self.faceButton = QtWidgets.QPushButton(self.groupBox)
        self.faceButton.setGeometry(QtCore.QRect(30, 100, 91, 41))
        self.faceButton.setObjectName("faceButton")
        self.carButton = QtWidgets.QPushButton(self.groupBox)
        self.carButton.setGeometry(QtCore.QRect(250, 40, 91, 41))
        self.carButton.setObjectName("carButton")
        self.QRButton = QtWidgets.QPushButton(self.groupBox)
        self.QRButton.setGeometry(QtCore.QRect(140, 40, 91, 41))
        self.QRButton.setObjectName("QRButton")
        self.fileButton = QtWidgets.QPushButton(self.groupBox)
        self.fileButton.setGeometry(QtCore.QRect(20, 30, 111, 61))
        self.fileButton.setObjectName("fileButton")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(740, 630, 381, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(270, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 20, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.imgButton.raise_()
        self.QRButton1.raise_()
        self.carButton1.raise_()
        self.faceButton1.raise_()
        self.inlabel.raise_()
        self.outlabel.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()

        self.retranslateUi(Dialog)
        self.QRButton.clicked.connect(Dialog.QRrecognize) # type: ignore
        self.carButton.clicked.connect(Dialog.carrecognize) # type: ignore
        self.faceButton.clicked.connect(Dialog.facedetect) # type: ignore
        self.imgButton.clicked.connect(Dialog.imgfix) # type: ignore
        self.QRButton1.clicked.connect(Dialog.QRrecognize1) # type: ignore
        self.carButton1.clicked.connect(Dialog.carrecognize1) # type: ignore
        self.faceButton1.clicked.connect(Dialog.facedetect1) # type: ignore
        self.fileButton.clicked.connect(Dialog.openFile) # type: ignore
        self.pushButton.clicked.connect(Dialog.inclear) # type: ignore
        self.pushButton_2.clicked.connect(Dialog.outclear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.imgButton.setText(_translate("Dialog", "图像拼接"))
        self.QRButton1.setText(_translate("Dialog", "二维码识别"))
        self.carButton1.setText(_translate("Dialog", "车牌识别"))
        self.faceButton1.setText(_translate("Dialog", "人脸检测"))
        self.inlabel.setText(_translate("Dialog", "in"))
        self.outlabel.setText(_translate("Dialog", "out"))
        self.groupBox.setTitle(_translate("Dialog", "基于文件的功能"))
        self.faceButton.setText(_translate("Dialog", "人脸检测"))
        self.carButton.setText(_translate("Dialog", "车牌识别"))
        self.QRButton.setText(_translate("Dialog", "二维码识别"))
        self.fileButton.setText(_translate("Dialog", "打开文件"))
        self.groupBox_2.setTitle(_translate("Dialog", "调用摄像头的功能"))
        self.pushButton.setText(_translate("Dialog", "停止播放"))
        self.pushButton_2.setText(_translate("Dialog", "停止播放"))
